name: Run flake8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake8-check:
    name: Run flake8
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: pip install flake8

      - name: Run flake8
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
