on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linters-check:
    name: Run Linters
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3

      - name: Install Python dependencies
        run: pip install flake8 black

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          black: true
