name: Run pydocstyle

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pydocstyle-check:
    name: Run pydocstyle
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.10

      - name: Install Python dependencies
        run: pip install pydocstyle

      - name: Run linters
        run: pydocstyle > report

      - name: Save report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pydocstyle-reports
          path: 'report'
          retention-days: 1
