on:
  push:
    [main]
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Get the version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
       
      - name: Build Project
        run: |
          python setup.py bdist_wheel

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: false
            prerelease: false

      - name: Upload Release Asset (wheel)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/teamvolik-${{ steps.get_version.outputs.version-without-v }}-py3-none-any.whl
          asset_name: teamvolik-${{ steps.get_version.outputs.version-without-v }}-py3-none-any.whl
          asset_content_type: application/x-wheel+zip
