name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.10

      - name: Install Python dependencies
        run: pip install unittest pysqlite3

      - name: Run tests
        run: python -m unittest
